### ISSUE TITLE
Remove repository?

### ISSUE THREAD

**Issue by ricardogobbosouza** [nuxt/nuxt-cli#2]
@Atinux, @pi0, @manniL 
Does this repository still make sense?

**Comment by pfalomorblab** [comment]
Hi @Atinux ,

first of all thank you (and your team) for creating nuxt. It's amazing!

since vue-cli **ui** is still in beta i would suggest to port it into the vue-cli waiting a beta nuxt-ui within a package (maybe this) that allows you to make great things like via the ui:

1. display a full tree of your available routes
1. make operations like creating new pages or components with boilerplates etc...
1. any useful information about current nuxt project

**Comment by atinux** [comment]
Thank you for your feedback @pfalomorblab 

I plan to use `nuxt-cli` as a global wrapper of `nuxt` local commands actually.

**Comment by atinux** [comment]
Nuxt CLI will be worked on for Nuxt 3 :)
